### ISSUE TITLE
need to fix the frontend to run the app locally (to remove some parts related to Stripe)

### ISSUE THREAD

**Issue by t-cool** [nlaz/flashcards-for-developers#99]
At first, please refer to this issue:
https://github.com/nlaz/flashcards-for-developers/issues/97

To run this app (flashcards-for-developers) locally, we need to fix the codes that are related to Stripe.

I made this issue to post it on Bountysource so that someone can fix the code and make it possible to run the app locally.

**Comment by t-cool** [comment]
@nlaz 
I put this issue on Bountysource putting $50.
https://www.bountysource.com/issues/68867147-need-to-fix-the-frontend-to-run-the-app-locally-to-remove-some-parts-related-to-stripe

It would be happy if you could solve this issue.
If you're busy, maybe someone else might give a PR to solve this issue.

**Comment by t-cool** [comment]
@nlaz
It seems that [dhamaniasad](https://github.com/dhamaniasad) has started dealing with this issue.

**Comment by dhamaniasad** [comment]
I've made a pull request for this error #100.

**Comment by t-cool** [comment]
@dhamaniasad 
Thank you for the PR!
I'll check it on my local environment from now.

**Comment by dhamaniasad** [comment]
@t-cool Sure, let me know if the issue has been resolved.

**Comment by t-cool** [comment]
@dhamaniasad 

Thank you for your help.  I started up mongo server by `mongod`, start the app's server by `yarn server`, and started the front end by `yarn web`.  

So far, I can see the top page of the app, but I cannot see any flashcards or decks when I 
access to `http://localhost:3000/decks`, which redirects me to its `404` page.

It seems that this app uses [Airtable](https://airtable.com) to fetch the flashcards data.  Do you think it's possible to simulate the flashcards locally?

**Comment by dhamaniasad** [comment]
@t-cool Yes, none of the cards are visible as the local database is empty. The cards that are on the site aren't made available in raw format, only through the site, @nlaz can confirm. 

However, if you set up an Airtable account, this is the schema of the data
**Card Decks**
```javascript
  airtableId: record.id,
  name: record.get("Name"),
  description: record.get("Description"),
  airtableCards: record.get("Cards"),
  type: record.get("Type"),
  source: record.get("Source"),
  difficulty: record.get("Difficulty"),
  stars: record.get("Stars"),
  createdTime: record.get("Created time"),
  upvotes: record.get("Upvotes"),
  downvotes: record.get("Downvotes"),
  pro: record.get("Pro") || false,
  new: record.get("New") || false,
```
**Cards**
```javascript
  airtableId: record.id,
  front: record.get("Front"),
  back: record.get("Back"),
  deckAirtableId: (record.get("Deck") || [])[0],
```

If you set up an Airtable with the same schema, you could add your Airtable API credentials in the config file and use that to seed your local database. Ofcourse you can also use local JSON files, but you would need to modify the codebase to do that.

**Comment by t-cool** [comment]
@dhamaniasad 
Thank you for your advice! 
I'll make an account on Airtable and try to follow those steps.
After I load the data from my account and see the result, I'll close this issue.

**Comment by t-cool** [comment]
I couldn't set up using Airtable.  
I think it's too complicated just to run the app locally.
I'll close this issue, and I'll make a new issue on this problem on my fork.
https://github.com/t-cool/flashcards-for-developers/issues/1

It would be happy if you would change the codes so that I can load the flashcard data from my local machine.  I'll post the new issue on Bountysource again.

**Comment by dhamaniasad** [comment]
Hey @t-cool!

Sure, atleast we got the front-end running. I'll definitely look into the ability to load data from JSON files and add that in. Will take it ahead on your fork of the repo from here :).

Happy to be of assistance :)

**Comment by nlaz** [comment]
Hi @t-cool and @dhamaniasad,

To clarify, you do not need Airtable to run the app locally. That was used as a convenience for us during development. You can add, delete, and edit flashcards directly in your database. You can use MongoDB tools to make this process easier.

I wouldn't suggest adding support for loading json directly from this project since that is likely to change in the future.

I would be happy to work with you though. Please reach out to my email at niko@flashcardsfordevelopers.com.
